# Generated by Django 4.1.6 on 2023-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_manager', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='goal',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
